package:
  name: mcu
  version: "1.0.0"

source:
  path: .

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
  run:
    # List your package dependencies here
    - python >= 3.6
    - numpy >= 1.15.2
    - scipy >= 1.1.0
    - matplotlib >= 3.0.1
    - spglib >= 1.15.1

test:
  # Define the dependencies required for running tests
  requires:
    - pytest

about:
  # Add any other relevant information about your package
  license: Apache 2.0
  home: https://github.com/hungpham2017/mcu

